/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderBookingsRouteImport } from './routes/provider.bookings'
import { Route as ProAdaezeRouteImport } from './routes/pro.adaeze'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/provider/bookings',
  path: '/provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAdaezeRoute = ProAdaezeRouteImport.update({
  id: '/pro/adaeze',
  path: '/pro/adaeze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/messages': typeof MessagesRoute
  '/wallet': typeof WalletRoute
  '/pro/adaeze': typeof ProAdaezeRoute
  '/provider/bookings': typeof ProviderBookingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/messages': typeof MessagesRoute
  '/wallet': typeof WalletRoute
  '/pro/adaeze': typeof ProAdaezeRoute
  '/provider/bookings': typeof ProviderBookingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/messages': typeof MessagesRoute
  '/wallet': typeof WalletRoute
  '/pro/adaeze': typeof ProAdaezeRoute
  '/provider/bookings': typeof ProviderBookingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/messages'
    | '/wallet'
    | '/pro/adaeze'
    | '/provider/bookings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/messages'
    | '/wallet'
    | '/pro/adaeze'
    | '/provider/bookings'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/messages'
    | '/wallet'
    | '/pro/adaeze'
    | '/provider/bookings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  MessagesRoute: typeof MessagesRoute
  WalletRoute: typeof WalletRoute
  ProAdaezeRoute: typeof ProAdaezeRoute
  ProviderBookingsRoute: typeof ProviderBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/bookings': {
      id: '/provider/bookings'
      path: '/provider/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/adaeze': {
      id: '/pro/adaeze'
      path: '/pro/adaeze'
      fullPath: '/pro/adaeze'
      preLoaderRoute: typeof ProAdaezeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  MessagesRoute: MessagesRoute,
  WalletRoute: WalletRoute,
  ProAdaezeRoute: ProAdaezeRoute,
  ProviderBookingsRoute: ProviderBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
