/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as InstantMatchRouteImport } from './routes/instant-match'
import { Route as BookRouteImport } from './routes/book'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderBookingsRouteImport } from './routes/provider.bookings'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as ProAdaezeRouteImport } from './routes/pro.adaeze'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const InstantMatchRoute = InstantMatchRouteImport.update({
  id: '/instant-match',
  path: '/instant-match',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/provider/bookings',
  path: '/provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAdaezeRoute = ProAdaezeRouteImport.update({
  id: '/pro/adaeze',
  path: '/pro/adaeze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/book': typeof BookRoute
  '/instant-match': typeof InstantMatchRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/pro/adaeze': typeof ProAdaezeRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/provider/bookings': typeof ProviderBookingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/book': typeof BookRoute
  '/instant-match': typeof InstantMatchRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/pro/adaeze': typeof ProAdaezeRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/provider/bookings': typeof ProviderBookingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/book': typeof BookRoute
  '/instant-match': typeof InstantMatchRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/pro/adaeze': typeof ProAdaezeRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/provider/bookings': typeof ProviderBookingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-studio'
    | '/book'
    | '/instant-match'
    | '/messages'
    | '/search'
    | '/wallet'
    | '/pro/adaeze'
    | '/pro/dashboard'
    | '/provider/bookings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-studio'
    | '/book'
    | '/instant-match'
    | '/messages'
    | '/search'
    | '/wallet'
    | '/pro/adaeze'
    | '/pro/dashboard'
    | '/provider/bookings'
  id:
    | '__root__'
    | '/'
    | '/ai-studio'
    | '/book'
    | '/instant-match'
    | '/messages'
    | '/search'
    | '/wallet'
    | '/pro/adaeze'
    | '/pro/dashboard'
    | '/provider/bookings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  BookRoute: typeof BookRoute
  InstantMatchRoute: typeof InstantMatchRoute
  MessagesRoute: typeof MessagesRoute
  SearchRoute: typeof SearchRoute
  WalletRoute: typeof WalletRoute
  ProAdaezeRoute: typeof ProAdaezeRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProviderBookingsRoute: typeof ProviderBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instant-match': {
      id: '/instant-match'
      path: '/instant-match'
      fullPath: '/instant-match'
      preLoaderRoute: typeof InstantMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/bookings': {
      id: '/provider/bookings'
      path: '/provider/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/adaeze': {
      id: '/pro/adaeze'
      path: '/pro/adaeze'
      fullPath: '/pro/adaeze'
      preLoaderRoute: typeof ProAdaezeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  BookRoute: BookRoute,
  InstantMatchRoute: InstantMatchRoute,
  MessagesRoute: MessagesRoute,
  SearchRoute: SearchRoute,
  WalletRoute: WalletRoute,
  ProAdaezeRoute: ProAdaezeRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProviderBookingsRoute: ProviderBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
